# Generated by Django 4.1.4 on 2022-12-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mKisan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="crop_type",
            field=models.CharField(default="Wheat", max_length=512),
        ),
        migrations.AddField(
            model_name="listing",
            name="pricing",
            field=models.CharField(
                choices=[("Auction", "auction"), ("Buy It Now", "buyitnow")],
                default="auction",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cassava", "Cassava"),
                    ("maize", "Maize"),
                    ("plantains", "Plantains"),
                    ("rice", "Rice"),
                    ("sorghum", "Sorghum"),
                    ("soybeans", "Soybeans"),
                    ("sweet", "Sweet"),
                    ("potatoes", "Potatoes"),
                    ("wheat", "Wheat"),
                    ("yams", "Yams"),
                ],
                max_length=60,
            ),
        ),
    ]
