# Generated by Django 4.1.4 on 2022-12-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mKisan", "0002_listing_crop_type_listing_pricing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="duration",
            field=models.IntegerField(default=7),
        ),
    ]
