# Generated by Django 4.1.4 on 2022-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mKisan", "0003_listing_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
